{% set version = "2.0.0rc4" %}

package:
  name: jupyter_server
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter_server/jupyter_server-{{ version }}.tar.gz
  sha256: 5c93c04b24340ab24d8190c5de52e5eace3eea91908d85bb05e96a0a93dde54a

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - jupyter-server = jupyter_server.serverapp:main

requirements:
  host:
    - hatchling >=1.11
    - pip
    - python >=3.8
  run:
    - anyio >=3.1.0,<4
    - argon2-cffi
    - jinja2
    - jupyter_client >=7.4.4
    - jupyter_core >=4.9.2
    - jupyter_events >=0.4.0
    - jupyter_server_terminals
    - nbconvert-core >=6.4.4  # avoid hard dependency on pandoc
    - nbformat >=5.2.0
    - packaging
    - prometheus_client
    - python >=3.8
    - pyzmq >=24
    - send2trash
    - terminado >=0.8.3
    - tornado >=6.2.0
    - traitlets >=5.1.0
    - websocket-client
    # - pywinpty  # [win]  # rely on terminado to get this to keep noarch


test:
  requires:
    - pip
    # test deps
    - coverage
    - ipykernel
    - pytest >=7.0
    - pytest-console-scripts
    - pytest-cov
    - pytest-timeout
    - pytest-tornasync
    - requests
  commands:
    - pip check
    - jupyter server -h
    - cd tests && pytest -vv --cov jupyter_server --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under 70
  imports:
    - jupyter_server
  downstreams:
    - jupyterlab >=3.2
    - jupyterlab_server >=2.14.0

about:
  home: https://jupyter-server.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: The backend—i.e. core services, APIs, and REST endpoints to Jupyter web applications.
  dev_url: https://github.com/jupyter/jupyter_server

extra:
  recipe-maintainers:
    - SylvainCorlay
    - maartenbreddels
    - blink1073
    - minrk
    - jasongrout
    - bollwyvl
    - Zsailer
