build_platform: {osx_arm64: osx_64}
conda_forge_output_validation: true
provider: {linux_aarch64: default, linux_ppc64le: azure, win: azure}
# `mamba` seems to fail with `test/downstreams`
conda_build_tool: conda-build
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
bot:
  inspection: hint-all
test: native_and_emulated
